backend:
  name: git-gateway
  branch: main # lub master w zależności od repozytorium

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "oferta"
    label: "Oferta"
    folder: "src/data/oferta"
    create: true
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Opis", name: "description", widget: "text" }